### ISSUE TITLE
Road map: week of Apr 10 

### ISSUE THREAD

**Issue by rskidmore1** [rskidmore1/meetup-clone#82]
#### Finishing features: 
- [ ] Events on groups links work 
- [ ] Attendees page on events
- [ ] Time System for events 
- [ ] Make all links go somewhere 
  - Like "Try me for free”, Message, Notifications
- [ ] Remove all admin features 
#### Next week
- [ ] UI reponsive
  - [ ] Header 
  - [ ] MAKE MORE
- [ ] Auth
